# Generated by Django 5.2.6 on 2025-10-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_syllabus'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='course_year',
            field=models.CharField(default='yet', max_length=4),
        ),
    ]
