# Generated by Django 5.2.6 on 2025-10-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_syllabus_course_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='course_department',
            field=models.CharField(default='学部不明', max_length=100),
        ),
    ]
